apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: musicbrainz
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: musicbrainz
    spec:
      containers:
      - env:
        - name: MUSICBRAINZ_USE_PROXY
          value: "1"
        name: musicbrainz
        image: musicbrainzdocker_musicbrainz:latest
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /media/dbdump
          name: postgresqldata-claim0
      restartPolicy: Always
      volumes:
      - name: postgresqldata-claim0
        persistentVolumeClaim:
          claimName: postgresqldata-claim0
status: {}
