apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: postgresql
  name: postgresql
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: postgresql
status:
  loadBalancer: {}
