apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: search
  name: search
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: search
status:
  loadBalancer: {}
